apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-transacciones
  labels:
    app: go-transacciones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-transacciones
  template:
    metadata:
      labels:
        app: go-transacciones
    spec:
      containers:
      - name: go-transacciones
        image: sampleacrhca.azurecr.io/go-transacciones:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: go-transacciones
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: go-transacciones
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-transacciones-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-transacciones
            port:
              number: 80