name: Build - Deploy to AKS
on:
    push:
        branches: [main]
    pull_request: 
        branches: [main]

env:
    AZURE_CONTAINER_REGISTRY: "sampleacrhca"
    CONTAINER_NAME: "go-transacciones"
    RESOURCE_GROUP: "free-skink-rg"
    CLUSTER_NAME: "free-skink-aks"
    DEPLOYMENT_MANIFEST_PATH: 'k8s/deployment.yaml'

jobs:
    buildAndDeploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.21'
            
            - name: Login to Azure
              uses: azure/login@v2
              with:
                creds: ${{secrets.AZURE_CREDENTIALS}}
            
            - name: Login to ACR
              run: |
                az acr login --name ${{env.AZURE_CONTAINER_REGISTRY}}
            
            - name: Build and push Docker image
              run: |
                docker build -t ${{env.AZURE_CONTAINER_REGISTRY}}.azurecr.io/${{env.CONTAINER_NAME}}:${{github.sha}} .
                docker push ${{env.AZURE_CONTAINER_REGISTRY}}.azurecr.io/${{env.CONTAINER_NAME}}:${{github.sha}}
            
            - name: Set AKS Context
              uses: azure/aks-set-context@v3
              with:
                resource-group: ${{env.RESOURCE_GROUP}}
                cluster-name: ${{env.CLUSTER_NAME}}
            
            - name: Deploy to AKS
              uses: azure/k8s-deploy@v4
              with:
                manifests: |
                  ${{env.DEPLOYMENT_MANIFEST_PATH}}
                images: |
                  ${{env.AZURE_CONTAINER_REGISTRY}}.azurecr.io/${{env.CONTAINER_NAME}}:${{github.sha}}
                namespace: ingress-nginx